force-app/main/default/objects/Coupon__c/Coupon__c.object-meta.xml
<CustomObject>
    <label>Coupon</label>
    <nameField>
        <displayFormat>CC-{00000}</displayFormat>
        <label>Coupon Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Coupons</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Coupon__c/fields/Amount__c.field-meta.xml
<CustomField>
    <fullName>Amount__c</fullName>
    <description>Enter valid Amount.</description>
    <inlineHelpText>Enter valid Amount.</inlineHelpText>
    <label>Amount</label>
    <precision>18</precision>
    <required>true</required>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Coupon__c/fields/Brand__c.field-meta.xml
<CustomField>
    <fullName>Brand__c</fullName>
    <label>Brand</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Amazon</fullName>
            </value>
            <value>
                <fullName>Flipkart</fullName>
            </value>
            <value>
                <fullName>Myntra</fullName>
            </value>
            <value>
                <fullName>Ajio</fullName>
            </value>
            <value>
                <fullName>Souled Store</fullName>
            </value>
            <value>
                <fullName>Pantaloons</fullName>
            </value>
            <value>
                <fullName>FBB</fullName>
            </value>
            <value>
                <fullName>Westside</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Coupon__c/fields/Case__c.field-meta.xml
<CustomField>
    <fullName>Case__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Case</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>Coupons</relationshipLabel>
    <relationshipName>Coupons</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Coupon__c/fields/Coupon_Code__c.field-meta.xml
<CustomField>
    <fullName>Coupon_Code__c</fullName>
    <description>Add a valid Coupon Code.</description>
    <externalId>true</externalId>
    <inlineHelpText>Add a valid Coupon Code.</inlineHelpText>
    <label>Coupon Code</label>
    <type>AutoNumber</type>
</CustomField>

force-app/main/default/objects/Coupon__c/fields/Expiry_Date__c.field-meta.xml
<CustomField>
    <fullName>Expiry_Date__c</fullName>
    <description>Enter valid date.</description>
    <inlineHelpText>Enter valid date.</inlineHelpText>
    <label>Expiry Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Coupon__c/fields/Issue_Date__c.field-meta.xml
<CustomField>
    <fullName>Issue_Date__c</fullName>
    <description>Enter Valid Date.</description>
    <inlineHelpText>Enter Valid Date.</inlineHelpText>
    <label>Issue Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Coupon__c/fields/Redeemed_Date__c.field-meta.xml
<CustomField>
    <fullName>Redeemed_Date__c</fullName>
    <description>Enter valid Date.</description>
    <inlineHelpText>Enter valid Date.</inlineHelpText>
    <label>Redeemed Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Coupon__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Valid</fullName>
            </value>
            <value>
                <fullName>Expired</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/CouponsManager.cls
@RestResource(urlMapping='/CouponsManager/*')
global with sharing class CouponsManager {
    //This is Post Method
    @HttpPost
    global static ID createCoupon(Decimal Amount, String Status, String IssueDate, String ExpiryDate,
                                  String RedeemedDate, String Brand, String cas){

                RestResponse response=RestContext.response; 
                //HttpResponse hres=new HttpResponse();
                Coupon__c newCoupon = new Coupon__c(
            					Amount__c = Amount,
        						Status__c = Status,
            					Issue_Date__c = Date.parse(IssueDate),
            					Expiry_Date__c = Date.parse(ExpiryDate),
            					Redeemed_Date__c = Date.parse(RedeemedDate),
          						Brand__c = Brand);
       
        insert newCoupon;
        return newCoupon.id;
}
    
    
    
    
    //This is get Method
    
/*    
    @HttpGet
    global static Coupon__c getCouponById(){
        
        RestRequest request=RestContext.request;
		RestResponse response=RestContext.response;
		String jsonString=request.requestBody.toString().trim();
        Coupon__c couponReq= (Coupon__c)JSON.deserializeStrict(jsonString, Coupon__c.class);
        
        if(couponReq !=NULL)
        {

			Coupon__c cop = [SELECT Coupon_Code__c,Status__c,Amount__c,Brand__c,Issue_Date__c,Expiry_Date__c FROM Coupon__c];
			// Coupon__c cop=[SELECT Coupon_Code__c,Status__c,Amount__c,Brand__c,IssueDate__c,ExpiryDate__c FROM Coupon__c
			// WHERE Id= :copuponReq];

}
        
        String coupId = request.requestURI.substring(request.requestURI.lastIndexOf('/')+1);
        Coupon__c coup = [SELECT Amount__c, Status__c, Issue_Date__c, Expiry_Date__c,Redeemed_Date__c, Case__c,
                          Brand__c FROM Coupon__c WHERE Id = :coupId];
        return coup;
    } 
*/

}